# Generated by Django 4.1.9 on 2023-07-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_number', models.CharField(max_length=50, verbose_name='Household Number')),
                ('date_accomplished', models.DateField(verbose_name='Date Accomplished')),
                ('prepared_by', models.CharField(max_length=50, verbose_name='Prepared by (Name of Household Head/Member')),
                ('certified_by', models.CharField(max_length=50, verbose_name='Certified Correct (Barangay Secretary)')),
                ('validated_by', models.CharField(max_length=50, verbose_name='Validated by (Punong Barangay)')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('extension_name', models.CharField(max_length=50, verbose_name='Extension Name')),
                ('place_of_birth', models.CharField(max_length=50, verbose_name='Place of Birth')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('sex', models.CharField(max_length=50, verbose_name='Sex')),
                ('civil_status', models.CharField(max_length=50, verbose_name='Civil Status')),
                ('citizenship', models.CharField(max_length=50, verbose_name='Citizenship')),
                ('occupation', models.CharField(max_length=50, verbose_name='Occupation')),
                ('house_no', models.CharField(max_length=50, verbose_name='House No.')),
                ('street_name', models.CharField(max_length=50, verbose_name='Street Name')),
                ('area_name', models.CharField(max_length=50, verbose_name='Subdivion Name/Zone/Sitio/Purok')),
                ('date_accomplished', models.DateField(verbose_name='Date Accomplished')),
                ('accomplished_by', models.CharField(max_length=50, verbose_name='Name of Person Accomplishing the Form')),
                ('attested_by', models.CharField(max_length=50, verbose_name='Attested by (Barangay Secretary)')),
                ('household_number', models.CharField(max_length=50, verbose_name='Household Number')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rbi.household', verbose_name='Household')),
            ],
        ),
    ]
