# Generated by Django 4.1.9 on 2023-07-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='accomplished_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of Person Accomplishing the Form'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='area_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subdivion Name/Zone/Sitio/Purok'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='attested_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Attested by (Barangay Secretary)'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Citizenship'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='civil_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Civil Status'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='date_accomplished',
            field=models.DateField(blank=True, null=True, verbose_name='Date Accomplished'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='extension_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Extension Name'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='house_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='House No.'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rbi.household', verbose_name='Household'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='household_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Household Number'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Place of Birth'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='street_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Street Name'),
        ),
    ]
